version: '3.8'

services:
  frontend:
    image: node:latest
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    image: node:latest
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3001:3001"
    command: npm start
